---

- name: SSO Realm management starting
  debug:
    msg:
      - "create_realms: {{create_realms}}"
      - "realm_output_dir:  {{realm_output_dir}}"
      - "realm_management_log_file = {{realm_output_dir}}/{{realm_provisioning_log_file}}"
      - "start and end realms = {{start_realm}}  {{end_realm}}"

- set_fact:
    retrieve_token_url: "https://sso-{{ocp_project}}.{{ocp_apps_domain}}/auth/realms/master/protocol/openid-connect/token"
- set_fact:
    create_realm_url: "https://sso-{{ocp_project}}.{{ocp_apps_domain}}/auth/admin/realms"
- set_fact:
    delete_realm_sub_url: "https://sso-{{ocp_project}}.{{ocp_apps_domain}}/auth/admin/realms"





# 1)  Get access and refresh OAuth tokens
- include: refreshOAuthTokens.yml


# 2)  Create or delete configurable number of realms
- name: "Loop through realm prep {{start_realm}} {{end_realm}}"
  include: realmPrep.yml realmId="realm{{item}}"
  loop: "{{ range(start_realm|int, end_realm|int + 1, 1)|list }}"




- name: Realm Rollout Complete
  debug:
    msg: Realm Rollout Complete
